{"name": "Updating", "status": "failed", "statusDetails": {"message": "AssertionError: Invalid input\nassert 415 == 200\n +  where 415 = <bound method ApiPet.connect_add_pet of <api_create.ApiPet object at 0x0000020F3B2E4610>>('/pet/92854776000')\n +    where <bound method ApiPet.connect_add_pet of <api_create.ApiPet object at 0x0000020F3B2E4610>> = <api_create.ApiPet object at 0x0000020F3B2E4610>.connect_add_pet\n +    and   '/pet/92854776000' = <test_api.TestApiExam object at 0x0000020F3B3727A0>.get_id_url", "trace": "self = <test_api.TestApiExam object at 0x0000020F3B3727A0>, check_add_pet = <api_create.ApiPet object at 0x0000020F3B2E4610>\n\n    @allure.title('Updating')\n    @allure.description('Updates a pet in the store form data')\n    def test_update_pet_by_id(self, check_add_pet):\n        with allure.step('Check status code'):\n>           assert check_add_pet.connect_add_pet(self.get_id_url) == 200, \"Invalid input\"\nE           AssertionError: Invalid input\nE           assert 415 == 200\nE            +  where 415 = <bound method ApiPet.connect_add_pet of <api_create.ApiPet object at 0x0000020F3B2E4610>>('/pet/92854776000')\nE            +    where <bound method ApiPet.connect_add_pet of <api_create.ApiPet object at 0x0000020F3B2E4610>> = <api_create.ApiPet object at 0x0000020F3B2E4610>.connect_add_pet\nE            +    and   '/pet/92854776000' = <test_api.TestApiExam object at 0x0000020F3B3727A0>.get_id_url\n\ntests\\test_api.py:62: AssertionError"}, "description": "Updates a pet in the store form data", "steps": [{"name": "Check status code", "status": "failed", "statusDetails": {"message": "AssertionError: Invalid input\nassert 415 == 200\n +  where 415 = <bound method ApiPet.connect_add_pet of <api_create.ApiPet object at 0x0000020F3B2E4610>>('/pet/92854776000')\n +    where <bound method ApiPet.connect_add_pet of <api_create.ApiPet object at 0x0000020F3B2E4610>> = <api_create.ApiPet object at 0x0000020F3B2E4610>.connect_add_pet\n +    and   '/pet/92854776000' = <test_api.TestApiExam object at 0x0000020F3B3727A0>.get_id_url\n", "trace": "  File \"D:\\PyProjects\\homework\\pythonProject\\tests\\test_api.py\", line 62, in test_update_pet_by_id\n    assert check_add_pet.connect_add_pet(self.get_id_url) == 200, \"Invalid input\"\n"}, "start": 1703694941453, "stop": 1703694942353}], "start": 1703694941453, "stop": 1703694942353, "uuid": "6692eb7c-d210-4467-999c-97a2685c3e9c", "historyId": "3fe3b20ce226798e261e528d4d2bb6c9", "testCaseId": "3fe3b20ce226798e261e528d4d2bb6c9", "fullName": "tests.test_api.TestApiExam#test_update_pet_by_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiExam"}, {"name": "host", "value": "DESKTOP-Q0K3D1C"}, {"name": "thread", "value": "15748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}