{"name": "Delete a pet from the store", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: 34 still exists\nassert 404 == 200\n +  where 404 = <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D10BCA0>>('/pet/', '34')\n +    where <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D10BCA0>> = <api_create.ApiPet object at 0x000002593D10BCA0>.delete_by_id\n +    and   '/pet/' = <test_api.TestApiExam object at 0x000002593D0D1420>.get_id_url\n +    and   '34' = str(34)", "trace": "self = <test_api.TestApiExam object at 0x000002593D0D1420>, create_pet_object = <api_create.ApiPet object at 0x000002593D10BCA0>, _id = 34\n\n    @allure.title(\"Delete a pet from the store\")\n    @allure.description(\"Check relevant response\")\n    @pytest.mark.xfail(strict=True)\n    @pytest.mark.parametrize(\"_id\", [4, 32, 34])\n    def test_delete_non_existed_pet(self, create_pet_object, _id):\n        with allure.step('Check status code'):\n>           assert create_pet_object.delete_by_id(self.get_id_url, str(_id)) == 200, f'{_id} still exists'\nE           AssertionError: 34 still exists\nE           assert 404 == 200\nE            +  where 404 = <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D10BCA0>>('/pet/', '34')\nE            +    where <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D10BCA0>> = <api_create.ApiPet object at 0x000002593D10BCA0>.delete_by_id\nE            +    and   '/pet/' = <test_api.TestApiExam object at 0x000002593D0D1420>.get_id_url\nE            +    and   '34' = str(34)\n\ntests\\test_api.py:86: AssertionError"}, "description": "Check relevant response", "steps": [{"name": "Check status code", "status": "failed", "statusDetails": {"message": "AssertionError: 34 still exists\nassert 404 == 200\n +  where 404 = <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D10BCA0>>('/pet/', '34')\n +    where <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D10BCA0>> = <api_create.ApiPet object at 0x000002593D10BCA0>.delete_by_id\n +    and   '/pet/' = <test_api.TestApiExam object at 0x000002593D0D1420>.get_id_url\n +    and   '34' = str(34)\n", "trace": "  File \"D:\\PyProjects\\homework\\pythonProject\\tests\\test_api.py\", line 86, in test_delete_non_existed_pet\n    assert create_pet_object.delete_by_id(self.get_id_url, str(_id)) == 200, f'{_id} still exists'\n"}, "start": 1703710490610, "stop": 1703710491363}], "parameters": [{"name": "_id", "value": "34"}], "start": 1703710490610, "stop": 1703710491363, "uuid": "36be5d63-adde-4093-8124-f65a0d308a26", "historyId": "ef072c24fddd9e0ddd197826654c9f28", "testCaseId": "3b38a9af0f65b31894ff5fd3280bd561", "fullName": "tests.test_api.TestApiExam#test_delete_non_existed_pet", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(strict=True)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiExam"}, {"name": "host", "value": "DESKTOP-Q0K3D1C"}, {"name": "thread", "value": "18048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}